parameters:

services:
    appConfiguration:
        class: Keboola\GoodDataWriter\Writer\AppConfiguration
        arguments: [%gooddata_writer%]
    gooddataModel:
        class: Keboola\GoodDataWriter\GoodData\Model
        arguments: [@appConfiguration]
    restApiS3Client:
        class: Keboola\GoodDataWriter\Service\S3Client
        arguments: [@appConfiguration, "RestAPI"]
    restApiLogFormatter:
        class: Keboola\GoodDataWriter\Service\RestAPILogFormatter
        arguments: [@restApiS3Client]
    restApiSyslogHandler:
        class: Monolog\Handler\SyslogHandler
        arguments: [%app_name%]
    restApiLogger:
        class: Monolog\Logger
        arguments: ["restApi"]
    restApiLoggerFactory:
        class: Keboola\GoodDataWriter\GoodData\RestApiLoggerFactory
        arguments: [@restApiLogger, @restApiSyslogHandler, @restApiLogFormatter]
    restApi:
        class: Keboola\GoodDataWriter\GoodData\RestApi
        arguments: [@gooddataModel, @logger, @restApiLoggerFactory]