parameters:

services:
  gooddata_writer.app_configuration:
    class: Keboola\GoodDataWriter\Writer\AppConfiguration
    arguments: [%app_name%, %storage_api.url%, %gooddata_writer%]
  gooddata_writer.gooddata_model:
    class: Keboola\GoodDataWriter\GoodData\Model
    arguments: [@gooddata_writer.app_configuration]

  gooddata_writer.rest_api.s3_client:
    class: Keboola\GoodDataWriter\Service\S3Client
    arguments: [@gooddata_writer.app_configuration, "RestAPI", @logger]
  gooddata_writer.rest_api.log_formatter:
    class: Keboola\GoodDataWriter\Service\RestAPILogFormatter
    arguments: [@gooddata_writer.rest_api.s3_client]
  gooddata_writer.rest_api.syslog_handler:
    class: Monolog\Handler\SyslogHandler
    arguments: [%app_name%]
  gooddata_writer.rest_api.logger_configurator:
    class: Keboola\GoodDataWriter\GoodData\RestApiLoggerConfigurator
    arguments: [@gooddata_writer.rest_api.syslog_handler, @gooddata_writer.rest_api.log_formatter]
  gooddata_writer.rest_api.logger:
    class: Monolog\Logger
    arguments: ["restApi"]
    configurator: ["@gooddata_writer.rest_api.logger_configurator", configure]
  gooddata_writer.rest_api:
    class: Keboola\GoodDataWriter\GoodData\RestApi
    arguments: [@gooddata_writer.app_configuration, @gooddata_writer.gooddata_model, @gooddata_writer.rest_api.logger]

  gooddata_writer.shared_storage:
    class: Keboola\GoodDataWriter\Writer\SharedStorage
    arguments: [@doctrine.dbal.default_connection, @syrup.encryptor]

  gooddata_writer.invitations_handler:
      class: Keboola\GoodDataWriter\GoodData\InvitationsHandler
      arguments: [@gooddata_writer.app_configuration, @gooddata_writer.shared_storage]

  gooddata_writer.job_executor:
    class: Keboola\GoodDataWriter\Writer\JobExecutor
    arguments: [@gooddata_writer.app_configuration, @gooddata_writer.shared_storage, @gooddata_writer.rest_api, @logger, @syrup.temp, @gooddata_writer.jobs_queue, @translator]

  gooddata_writer.jobs_queue:
    class: Keboola\GoodDataWriter\Service\Queue
    arguments: [@gooddata_writer.app_configuration]
