parameters:
#    syrup_db.example.class: Syrup\DbBundle\Example

services:
#    syrup_db.example:
#        class: %syrup_db.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    gooddata_writer.sso:
        class: Keboola\GoodDataWriter\GoodData\SSO
        arguments: [%gooddata_writer%, @kernel]
