parameters:

services:

  gooddata_writer.s3_client:
    class: Keboola\GoodDataWriter\Service\S3Client
    arguments: [%uploader%]

  gooddata_writer.rest_api.log_formatter:
    class: Keboola\GoodDataWriter\Monolog\Formatter\RestAPILogFormatter
    arguments: [@syrup.s3_uploader]
  gooddata_writer.rest_api.syslog_handler:
    class: Monolog\Handler\SyslogHandler
    arguments: [%app_name%]
  gooddata_writer.rest_api.logger_configurator:
    class: Keboola\GoodDataWriter\GoodData\RestApiLoggerConfigurator
    arguments: [@gooddata_writer.rest_api.syslog_handler, @gooddata_writer.rest_api.log_formatter]
  gooddata_writer.rest_api.logger:
    class: Monolog\Logger
    arguments: ["restApi"]
    configurator: ["@gooddata_writer.rest_api.logger_configurator", configure]

  gooddata_writer.rest_api:
    class: Keboola\GoodDataWriter\GoodData\RestApi
    arguments: [%app_name%, @gooddata_writer.rest_api.logger]

  gooddata_writer.shared_storage:
    class: Keboola\GoodDataWriter\Writer\SharedStorage
    arguments: [@doctrine.dbal.default_connection, @syrup.encryptor]

  gooddata_writer.invitations_handler:
      class: Keboola\GoodDataWriter\GoodData\InvitationsHandler
      arguments: [%gdwr_scripts_path%, %gdwr_invitations%, @gooddata_writer.shared_storage]

  gooddata_writer.job_executor:
    class: Keboola\GoodDataWriter\Writer\JobExecutor
    arguments:
      - %gdwr_scripts_path%
      - %user_agent%
      - %gdwr_gd%
      - @gooddata_writer.shared_storage
      - @gooddata_writer.rest_api
      - @logger
      - @syrup.temp
      - @syrup.queue_factory
      - @translator
      - @syrup.s3_uploader
      - @gooddata_writer.s3_client
